<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // In mysql by default, the utf8_unicode_ci is case-insensitive, so the slug generator
        // would occasionally cause collisions. This changes the column to be case sensitive so
        // overlapping output should not occur
        // i.e., previously, SUXcoNQRgc and SuxcoNQRgc were generated by Sqids and would cause a collision
        Schema::table('scouts', function(Blueprint $table) {
            $table->string('slug')->nullable()->default(null)->charset('utf8mb4')->collation('utf8mb4_bin')->change();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('scouts', function(Blueprint $table) {
            $table->string('slug')->nullable()->default(null)->charset('utf8mb4')->collation('utf8mb4_unicode_ci')->change();
        });
    }
};
